### ISSUE TITLE
Folder structure becomes flat when uploading

### ISSUE THREAD

**Issue by code-sport** [bxb100/action-upload-webdav#51]
I would like to upload a folder via WebDav, keeping the folder structure intact. Which is not the case right now.

The configuration looks like this:
```YAML
    - name: Upload WebDAV
      uses: bxb100/action-upload-webdav@v0.0.4
      with:
        webdav_address: ${{secrets.NEXTCLOUD_ADDRESS}}
        webdav_username: ${{secrets.NEXTCLOUD_USERNAME}}
        webdav_password: ${{secrets.NEXTCLOUD_PASSWORD}}
        webdav_upload_path: "/AT/dev/${{ env.VersionNumer }}/manual"
        files: |
          ${{ env.working-directory }}/site/**
        fail_on_unmatched_files: true
```

How do I specify that the order structure should be kept?
