### ISSUE TITLE
Action fails with keep_structure on apache

### ISSUE THREAD

**Issue by elfrijo** [bxb100/action-upload-webdav#52]
The actions fails when used with keep_structure=true on apache httpd and multiple files inside a subdirectory.

it seems that the action will try to create subdirectories for every file it tries to put.
When a directory already exists, httpd will return 405 and the action aborts.

```
10.30.134.12 - test [18/Jan/2023:11:26:47 +0100] "PROPFIND / HTTP/1.1" 207 1089 "-" "axios/0.27.2"
10.30.134.12 - test [18/Jan/2023:11:26:48 +0100] "PROPFIND /_nuxt HTTP/1.1" 404 396 "-" "axios/0.27.2"
10.30.134.12 - test [18/Jan/2023:11:26:48 +0100] "PUT /200.html HTTP/1.1" 201 483 "-" "axios/0.27.2"
10.30.134.12 - test [18/Jan/2023:11:26:48 +0100] "PUT /404.html HTTP/1.1" 201 483 "-" "axios/0.27.2"
10.30.134.12 - test [18/Jan/2023:11:26:49 +0100] "MKCOL /_nuxt/ HTTP/1.1" 201 481 "-" "axios/0.27.2"
10.30.134.12 - test [18/Jan/2023:11:26:49 +0100] "PROPFIND /_nuxt HTTP/1.1" 301 492 "-" "axios/0.27.2"
10.30.134.12 - test [18/Jan/2023:11:26:49 +0100] "PUT /_nuxt/Accordeon.20c6715a.css HTTP/1.1" 201 523 "-" "axios/0.27.2"
10.30.134.12 - test [18/Jan/2023:11:26:51 +0100] "MKCOL /_nuxt/ HTTP/1.1" 405 440 "-" "axios/0.27.2"
```

A workaround would be an option to ignore errors and keep uploading.
However, such a behavior would also work around (or hide) other problems in bigger uploads.

For reference, this is my action config:
```
      - name: Deployment          
        uses: bxb100/action-upload-webdav@main
        with:
          webdav_address: "https://server.tld"
          webdav_username: ${{ secrets.WEB_DAV_USER }}
          webdav_password: ${{ secrets.WEB_DAV_PASSWORD }}
          webdav_upload_path: "/"
          files: ".output/public/*"
          keep_structure: true
```

This the dav vhost/config:
```
  <Directory /srv/public/docroot>
    DirectoryIndex disabled
    AllowMethods HEAD GET POST CONNECT PUT DELETE OPTIONS PROPFIND PROPPATCH MKCOL COPY MOVE LOCK UNLOCK TRACE
    DAV on
    AuthType Basic
    AuthName "webdav"
    AuthUserFile /srv/config/restricted.htpasswd
    Require valid-user
  </Directory>
```
