### ISSUE TITLE
Action doesn't fail on failed uploading

### ISSUE THREAD

**Issue by yanosz** [bxb100/action-upload-webdav#56]
Hei,

I've just played with your action. I noticed that a error while uploading still results in a green pipeline.

Server logs HTTP-401:

```
webdav.fieldtracks.org:80 172.16.5.1 - fieldtracks [22/Jan/2023:17:18:52 +0000] "PUT /JellingStone/JellingStone-b22b81a7be65a0341758024bcc8aef3b8f03975e%2Bgh3980720524.zip HTTP/1.0" 401 704 "-" "axios/0.27.2"
```

Action output is:
```
Run bxb100/action-upload-webdav@d19f1edf785abf4b0b7f818ba46b6dba9b0334c6
  with:
    webdav_address: https://webdav.***.org
    webdav_username: ***
    webdav_password: ***
    webdav_upload_path: /JellingStone
    files: JellingStone*.zip
    keep_structure: false
    fail_on_unmatched_files: false
  env:
    AUTOMATIC_RELEASES_TAG: current-main
Current directory: /home/runner/work/JellingStone/JellingStone
📦 Uploading /home/runner/work/JellingStone/JellingStone/JellingStone-b22b81a7be65a0341758024bcc8aef3b8f03975e+gh3980720524.zip to /JellingStone/JellingStone-b22b81a7be65a0341758024bcc8aef3b8f03975e+gh3980720524.zip
```

I'd expect the action to fail if the server responds with HTTP-401.
